server:
  port: 8189
  servlet:
    context-path: /
    session:
      timeout: 60s
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      ddl-auto: none
      temp:
        use-jdbc_metadata_defaults: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:securitydb;MODE=PostgreSQL
    username: sa
    password: